import type { DhikrItem } from "./types";

export const DHIKR_CATALOG: DhikrItem[] = [
  {
    id: "subhanallah",
    slug: "subhanallah",
    arabic: "سُبْحَانَ اللَّهِ",
    transliteration: "Subhanallah",
    translation: "Glory be to Allah.",
    recommendedCount: 33,
    categories: ["general", "after-salah", "before-sleep", "morning", "evening"],
    source: "Sahih Muslim, the tasbih after salah",
  },
  {
    id: "alhamdulillah",
    slug: "alhamdulillah",
    arabic: "الْحَمْدُ لِلَّهِ",
    transliteration: "Alhamdulillah",
    translation: "All praise is for Allah.",
    recommendedCount: 33,
    categories: ["general", "after-salah", "before-sleep"],
    source: "Sahih Muslim, the tasbih after salah",
  },
  {
    id: "allahu-akbar",
    slug: "allahu-akbar",
    arabic: "اللَّهُ أَكْبَرُ",
    transliteration: "Allahu Akbar",
    translation: "Allah is the Greatest.",
    recommendedCount: 34,
    categories: ["general", "after-salah", "before-sleep"],
    source: "Sahih Muslim, completing one hundred after the prayer",
  },
  {
    id: "la-ilaha-illallah",
    slug: "la-ilaha-illallah",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ",
    transliteration: "La ilaha illallah",
    translation: "There is no god but Allah.",
    recommendedCount: 100,
    categories: ["general", "morning", "evening", "quranic"],
    source: "The statement of tawhid, recited in many authentic adhkar",
  },
  {
    id: "tawhid-long",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa 'ala kulli shay'in qadir",
    translation: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs the dominion and all praise, and He is over all things competent.",
    recommendedCount: 10,
    categories: ["morning", "evening", "after-salah", "general"],
    source: "Sahih al-Bukhari and Sahih Muslim",
  },
  {
    id: "astaghfirullah",
    slug: "astaghfirullah",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    transliteration: "Astaghfirullah",
    translation: "I seek Allah's forgiveness.",
    recommendedCount: 100,
    categories: ["istighfar", "after-salah", "general"],
    source: "Sahih Muslim: seeking forgiveness three times after the taslim",
  },
  {
    id: "sayyid-al-istighfar",
    slug: "sayyid-al-istighfar",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transliteration: "Allahumma anta Rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya, wa abu'u bidhanbi faghfir li, fa innahu la yaghfirudh-dhunuba illa ant",
    translation: "O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant. I keep Your covenant and promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me. None forgives sins except You.",
    recommendedCount: 1,
    categories: ["istighfar", "morning", "evening"],
    source: "Sahih al-Bukhari, the master supplication for forgiveness",
  },
  {
    id: "salawat",
    slug: "salawat",
    arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ",
    transliteration: "Allahumma salli 'ala Muhammad",
    translation: "O Allah, send blessings upon Muhammad.",
    recommendedCount: 10,
    categories: ["salawat", "general"],
    source: "The command to send blessings upon the Prophet, Quran 33:56",
  },
  {
    id: "subhanallahi-wa-bihamdihi",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "Subhanallahi wa bihamdih",
    translation: "Glory be to Allah and praise is His.",
    recommendedCount: 100,
    categories: ["morning", "evening", "general"],
    source: "Sahih Muslim: two phrases light on the tongue and heavy on the Scale",
  },
  {
    id: "allahumma-bika-asbahna",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namut, wa ilaykan-nushur",
    translation: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.",
    recommendedCount: 1,
    categories: ["morning", "after-waking"],
    source: "Sunan Abi Dawud and Jami' at-Tirmidhi",
  },
  {
    id: "allahumma-bika-amsayna",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ",
    transliteration: "Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namut, wa ilaykal-masir",
    translation: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the return.",
    recommendedCount: 1,
    categories: ["evening"],
    source: "Sunan Abi Dawud and Jami' at-Tirmidhi, the evening wording",
  },
  {
    id: "hasbiyallah",
    arabic: "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "Hasbiyallahu la ilaha illa Huwa, 'alayhi tawakkaltu, wa Huwa Rabbul-'Arshil-'Azim",
    translation: "Allah is sufficient for me. None has the right to be worshipped except Him. Upon Him I rely, and He is the Lord of the Mighty Throne.",
    recommendedCount: 7,
    categories: ["morning", "evening", "quranic"],
    source: "Sunan Abi Dawud; the wording echoes Quran 9:129",
  },
  {
    id: "audhu-bikalimatillah",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    recommendedCount: 3,
    categories: ["evening", "before-sleep"],
    source: "Sahih Muslim",
  },
  {
    id: "ayat-al-kursi",
    slug: "ayat-al-kursi",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum...",
    translation: "Allah — there is no god except Him, the Ever-Living, the Sustainer of all. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth.",
    recommendedCount: 1,
    categories: ["quranic", "morning", "evening", "before-sleep", "after-salah"],
    source: "Quran 2:255; Sahih al-Bukhari on reciting it before sleep and after prayer in related reports",
  },
  {
    id: "al-ikhlas",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    transliteration: "Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.",
    translation: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, and there is none comparable to Him.",
    recommendedCount: 3,
    categories: ["quranic", "morning", "evening", "before-sleep"],
    source: "Quran 112; Sunan Abi Dawud and Jami' at-Tirmidhi for the morning and evening",
  },
  {
    id: "al-falaq",
    arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
    transliteration: "Qul a'udhu bi Rabbil-falaq...",
    translation: "Say: I seek refuge in the Lord of daybreak, from the evil of what He created, and from the evil of darkness when it settles, and from the evil of those who blow on knots, and from the evil of an envier when he envies.",
    recommendedCount: 3,
    categories: ["quranic", "morning", "evening", "before-sleep"],
    source: "Quran 113; recited with the two sister surahs in the morning and evening",
  },
  {
    id: "an-nas",
    arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
    transliteration: "Qul a'udhu bi Rabbin-nas...",
    translation: "Say: I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer who whispers in the breasts of mankind, from among jinn and mankind.",
    recommendedCount: 3,
    categories: ["quranic", "morning", "evening", "before-sleep"],
    source: "Quran 114; recited with Al-Ikhlas and Al-Falaq",
  },
  {
    id: "waking-dua",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdulillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    translation: "All praise is for Allah who gave us life after having taken it from us, and to Him is the resurrection.",
    recommendedCount: 1,
    categories: ["after-waking"],
    source: "Sahih al-Bukhari",
  },
  {
    id: "sleep-dua",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Your name, O Allah, I die and I live.",
    recommendedCount: 1,
    categories: ["before-sleep"],
    source: "Sahih al-Bukhari",
  },
  {
    id: "antas-salam",
    arabic: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Allahumma antas-salamu wa minkas-salam, tabarakta ya Dhal-Jalali wal-Ikram",
    translation: "O Allah, You are Peace and from You is peace. Blessed are You, O Owner of majesty and honour.",
    recommendedCount: 1,
    categories: ["after-salah"],
    source: "Sahih Muslim, said after the taslim",
  },
  {
    id: "baqarah-closing",
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ ... لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
    transliteration: "Amanar-Rasulu... La yukallifullahu nafsan illa wus'aha...",
    translation: "The Messenger has believed in what was revealed to him from his Lord, and so have the believers... Allah does not charge a soul except with what it can bear.",
    recommendedCount: 1,
    categories: ["quranic", "before-sleep"],
    source: "Quran 2:285–286; Sahih al-Bukhari on reciting them at night",
  },
];

export const CATEGORY_LABELS: Record<DhikrItem["categories"][number], string> = {
  general: "General Dhikr",
  morning: "Morning",
  evening: "Evening",
  "after-salah": "After Salah",
  "before-sleep": "Before Sleep",
  "after-waking": "After Waking",
  istighfar: "Istighfar",
  salawat: "Salawat",
  quranic: "Quranic Dhikr",
};

export function getDhikr(id: string) {
  return DHIKR_CATALOG.find((item) => item.id === id);
}

export function getDhikrBySlug(slug: string) {
  return DHIKR_CATALOG.find((item) => item.slug === slug);
}
